version: "3.9"

services:
  agent_a:
    build: ./agent_a
    ports:
      - "8002:8002"
      - "8602:8602"   # Update server port
      - "8502:8502"   # Sync listener port
    volumes:
      - ./certs:/certs
    command: ["python", "-u", "app.py"]


  agent_b:
    build: ./agent_b
    ports:
      - "8001:8001"
      - "8601:8601"
      - "8501:8501"
    volumes:
      - ./certs:/certs
    command: ["python", "-u", "app.py"]
    
  agent_s:
    build: ./agent_s
    ports:
      - "8003:8003"
      - "8603:8603"
      - "8503:8503" 

    volumes:
      - ./certs:/certs
    command: ["python", "-u", "app.py"]

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODEL=llama3:8b   # Change to gpt-oss:latest, llama3:70b, etc
    entrypoint: >
      sh -c "ollama serve &
             until ollama pull $OLLAMA_MODEL; do
               echo 'retrying pull...';
               sleep 5;
             done;
             tail -f /dev/null"


  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


  populate-emails:
    build: ./testSetup
    depends_on:
      - mongo
    command: sh -c "sleep 5 && python populateEmails.py"


  populate-eggs:
    build: ./testSetup
    depends_on:
      - mongo
    command: sh -c "sleep 5 && python populateEggPrice.py"


volumes:
  ollama_data:
  mongo-data:

